version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: next
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: turbo
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
